server:
  port: 9001
spring:
  application:
    name: daniu-sellergoods
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/daniudb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
      password: admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
feign:
  hystrix:
    enabled: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰式编写规范
  type-aliases-package: com.jeff.sellergoods.pojo
# 配置sql打印日志
logging:
  level:
    com:
      jeff:
        debug