server:
  port: 9100
spring:
  application:
    name: user-auth
  datasource:
    url: jdbc:mysql://localhost/daniudb
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  redis:
    host: 192.168.110.128
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
encrypt:
  key-store:
    location: classpath:daniu.jks  #秘钥文件名
    alias: daniu  #别名
    password: daniu123  #密码
    secret: daniu123 #密钥库的访问密码
auth:
  ttl: 3600  #token过期时间
  clientId: admin  #客户端账号
  clientSecret: admin #客户端密码
  cookieDomain: localhost  #cookie域名
  cookieMaxAge: -1     #cookie有效期
# 开启Feign的熔断功能
feign:
  hystrix:
    enabled: true
#总连接超时时间=（切换服务实例次数+1）*（每个实例重试次数+1）*连接超时时间
USER: #服务名称
  ribbon:
    #配置指定服务的负载均衡策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    # Ribbon的连接超时时间
    ConnectTimeout: 2000
    # Ribbon的数据读取超时时间
    ReadTimeout: 2000
    # 是否对所有操作都进行重试
    OkToRetryOnAllOperations: true
    # 切换实例的重试次数
    MaxAutoRetriesNextServer: 1
    # 对当前实例的重试次数
    MaxAutoRetries: 1
#设定Hystrix熔断超时时间 ，理论上熔断时间应该大于总连接超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000