spring:
  application:
    name: search-web
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true
server:
  port: 8101
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100000
