server:
  port: 9005
spring:
  application:
    name: search
  elasticsearch:
    rest:
      uris: 192.168.110.128:9200
eureka:
  client:
    service-url:
      defualtZone: http://127.0.0.1:8761/eureka
feign:
  hystrix:
    enabled: true
#超时配置
ribbon:
  ReadTimeout: 300000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120s